using TMPro;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UI;

public class IntroManager : MonoBehaviour
{
    [Header("버튼")]
    [SerializeField] private Button playButton;
    [SerializeField] private Button createButton;

    [Header("씬 이름")]
    [SerializeField] private string songSelectScene  = "SongSelect";
    [SerializeField] private string songCreatorScene = "SongCreator";

    private void Start()
    {
        playButton.onClick.AddListener(() => SceneManager.LoadScene(songSelectScene));
        createButton.onClick.AddListener(() => SceneManager.LoadScene(songCreatorScene));
    }
}
